services:
  - type: web
    name: Backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    # Plan gratuito, NO incluye disco persistente.La DB SQLite se borra en cada deploy/restart.
    plan: free
    # Variables de entorno
    envVars:
      - key: PORT
        value: 10000   # Puerto por defecto
